#!/usr/bin/bash
declare -a medium_sudoku_puzzles
#some medium puzzles to test
medium_sudoku_puzzles[${#medium_sudoku_puzzles[@]}]="0000847b216e"
medium_sudoku_puzzles[${#medium_sudoku_puzzles[@]}]="0000c45fb232"
medium_sudoku_puzzles[${#medium_sudoku_puzzles[@]}]="0000fc7c6b96"
medium_sudoku_puzzles[${#medium_sudoku_puzzles[@]}]="00010f10503b"
medium_sudoku_puzzles[${#medium_sudoku_puzzles[@]}]="0001d8f677e4"
medium_sudoku_puzzles[${#medium_sudoku_puzzles[@]}]="0001e494a5b8"
medium_sudoku_puzzles[${#medium_sudoku_puzzles[@]}]="00020ac6da1f"
medium_sudoku_puzzles[${#medium_sudoku_puzzles[@]}]="00021acb2bbe"
medium_sudoku_puzzles[${#medium_sudoku_puzzles[@]}]="00024d60bdaf"
medium_sudoku_puzzles[${#medium_sudoku_puzzles[@]}]="000293df085f"
#make compile main sudoku solving C program
make clean && make
#set variables
stats_file="./benchmark/medium/stats-$$.txt"
sum_exec=0.0
sum_cost=0
sum_pow_exec=0.0
sum_exec_cost=0.0
n=0
#try the medium puzzles
for i in "${medium_sudoku_puzzles[@]}"
do
    result=$(./bin/main "medium.txt" "$i")
    echo -e "$result"
    #get the execution time for the x axis and the final cost of the algorithm for the y axis
    exec_time=$(echo "$result" | grep ">> CPU Execution time of the sudoku solving simulation :" | awk 'NF>1{print $NF}')
    end_cost=$(echo "$result" | grep ">> Best solution (lowest cost) found during the execution of the simulation :" | awk 'NF>1{print $NF}')
    echo "$exec_time $end_cost" >> "$stats_file"
    #sum_exec=$(echo "$sum_exec + $exec_time" | bc -l)
    #sum_cost=$(echo "$sum_cost + $end_cost" | bc -l)
    #sum_pow_exec=$(echo "$sum_pow_exec + $exec_time^2" | bc -l)
    #sum_exec_cost=$(echo "$sum_exec_cost + $exec_time * $end_cost" | bc -l)
    #n+=1
done
#calculate m and b for standard curve
#https://www.statisticshowto.com/probability-and-statistics/regression-analysis/find-a-linear-regression-equation/
#m=$(echo "($n * $sum_exec_cost - $sum_exec * $sum_cost) / ($n * $sum_pow_exec - $sum_exec^2)" | bc -l)
#b=$(echo "($sum_cost - $m * $sum_exec) / $n" | bc -l)
#echo -e " $m $b"
#create benchmark graph
./bin/benchmark "2" "$stats_file" #"$m" "$b"