#!/usr/bin/bash
declare -a medium_sudoku_puzzles
#some medium puzzles to test
medium_sudoku_puzzles[${#medium_sudoku_puzzles[@]}]="0000847b216e"
medium_sudoku_puzzles[${#medium_sudoku_puzzles[@]}]="0000c45fb232"
medium_sudoku_puzzles[${#medium_sudoku_puzzles[@]}]="0000fc7c6b96"
medium_sudoku_puzzles[${#medium_sudoku_puzzles[@]}]="00010f10503b"
medium_sudoku_puzzles[${#medium_sudoku_puzzles[@]}]="0001d8f677e4"
medium_sudoku_puzzles[${#medium_sudoku_puzzles[@]}]="0001e494a5b8"
medium_sudoku_puzzles[${#medium_sudoku_puzzles[@]}]="00020ac6da1f"
medium_sudoku_puzzles[${#medium_sudoku_puzzles[@]}]="00021acb2bbe"
medium_sudoku_puzzles[${#medium_sudoku_puzzles[@]}]="00024d60bdaf"
medium_sudoku_puzzles[${#medium_sudoku_puzzles[@]}]="000293df085f"
#make compile main sudoku solving C program
make clean && make
#try the medium puzzles
for i in "${medium_sudoku_puzzles[@]}"
do
    ./bin/main "medium.txt" "$i"
done